"""
Configuration and constants for roAp asteroseismic analysis.
"""

import os
from pathlib import Path

# Project root
PROJECT_ROOT = Path(__file__).parent.parent.parent

# Data directories (INPUT - downloaded separately, ignored by git)
DATA_DIR = PROJECT_ROOT / "data"
CSV_DIR = DATA_DIR / "lightcurves"

# MESA evolutionary tracks are small and version-controlled at the repo root.
SEQUENCES_DIR = PROJECT_ROOT / "sequences"

# Results directories (OUTPUT - generated by analysis, ignored by git)
RESULTS_DIR = PROJECT_ROOT / "results"
TABLES_DIR = RESULTS_DIR / "tables"
FIGURES_DIR = RESULTS_DIR / "figures"
FIGURES_HR_DIR = FIGURES_DIR / "hr_diagram"
FIGURES_PERIODOGRAM_DIR = FIGURES_DIR / "periodograms"
FIGURES_LC_DIR = FIGURES_DIR / "lightcurves"

# Ensure output/input directories exist (SEQUENCES_DIR is tracked in git, not created here)
for directory in [CSV_DIR, TABLES_DIR, FIGURES_HR_DIR, FIGURES_PERIODOGRAM_DIR, FIGURES_LC_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

# Stellar evolution track configurations
TRACK_MASSES = [1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.5]
TRACK_METALLICITY = "z019"  # Z ≈ 0.019, solar metallicity

# roAp frequency ranges (in µHz and 1/days)
ROAP_FREQ_RANGE_UHHZ = (100, 5000)  # typical range in microhertz
ROAP_FREQ_RANGE_D1 = (0.001, 0.057)  # typical range in 1/days

# Frequency unit conversion: 1 cycle/day = 1/86400 Hz = 11.57407 µHz
D1_TO_UHZ = 1e6 / 86400.0  # ≈ 11.57407 µHz per (day⁻¹)

# SNR threshold for significant peaks
SNR_THRESHOLD = 4.0

# Periodogram parameters
LOMBSCARGLE_OVERSAMPLE = 5
AMPLITUDE_NORMALIZATION = 'amplitude'  # Return amplitudes in ppm

# HR Diagram parameters (Nature-style)
TEFF_COLOR = "#2E86AB"  # Professional blue
TRACK_COLOR = "#9CA3AF" # Soft gray
TRACK_ALPHA = 0.35
